package enum

enum class SearchAlgorithmName {
    BREADTH_FIRST_SEARCH,
    DEPTH_FIRST_SEARCH,
    DEPTH_LIMITED_SEARCH,
    ITERATIVE_DEPENDING_SEARCH,
    BIDIRECTIONAL_SEARCH,
    GREEDY_FIRST_BEST,
    A_STAR;
}
